# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GoldCoins.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from GoldCoinsTelaVitoria import Ui_TelaVitoria
from GoldCoinsTelaInfoDaConta import Ui_TelaInfoConta
import resources

class Ui_TelaInicial(object):
    def OpenVictoryWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_TelaVitoria()
        self.ui.setupUi(self.window)
        self.window.show()

    def OpenAccountInfo(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_TelaInfoConta()
        self.ui.setupUi(self.window)
        self.window.show()


    def setupUi(self, TelaInicial):
        TelaInicial.setObjectName("TelaInicial")
        TelaInicial.resize(1005, 694)
        self.centralwidget = QtWidgets.QWidget(TelaInicial)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top = QtWidgets.QFrame(self.centralwidget)
        self.top.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top.setStyleSheet("background-color: rgb(251, 190, 119);")
        self.top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top.setObjectName("top")
        self.verticalLayout.addWidget(self.top)
        self.container = QtWidgets.QFrame(self.centralwidget)
        self.container.setStyleSheet("background-color: rgb(251, 190, 119);")
        self.container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.container)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main = QtWidgets.QFrame(self.container)
        self.main.setMaximumSize(QtCore.QSize(450, 650))
        self.main.setStyleSheet("background-color: rgb(255, 255, 255); border-radius: 10px;")
        self.main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.StartButton = QtWidgets.QPushButton(self.main, clicked = lambda: self.OpenVictoryWindow())
        self.StartButton.setGeometry(QtCore.QRect(125, 320, 201, 71))
        self.StartButton.setMaximumSize(QtCore.QSize(201, 75))
        self.StartButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StartButton.setStyleSheet("QPushButton {\n"
"    color: #fff;\n"
"    background-color: #81BAFD;\n"
"    font-size: 32px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #738FF0;\n"
"}\n"
"\n"
"")
        self.StartButton.setObjectName("StartButton")
        self.label_12 = QtWidgets.QLabel(self.main)
        self.label_12.setGeometry(QtCore.QRect(130, 480, 201, 31))
        self.label_12.setMaximumSize(QtCore.QSize(201, 31))
        self.label_12.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(72, 63, 51);\n"
"font-weight: bold;")
        self.label_12.setObjectName("label_12")
        self.LoginButton = QtWidgets.QPushButton(self.main, clicked = lambda: self.OpenAccountInfo())
        self.LoginButton.setGeometry(QtCore.QRect(175, 520, 101, 41))
        self.LoginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LoginButton.setStyleSheet("QPushButton {\n"
"background-color: #fff;\n"
"color: #81BAFD;\n"
"border-radius: 5px;\n"
"border: 2px solid #81BAFD;\n"
"font-weight: bold;\n"
"font-size: 18px;\n"
"}\n"
"\n"
"")
        self.LoginButton.setObjectName("LoginButton")
        self.label = QtWidgets.QLabel(self.main)
        self.label.setGeometry(QtCore.QRect(77, 60, 301, 201))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Logo/IconeGoldCoins.png"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.main)
        self.verticalLayout.addWidget(self.container)
        self.bot = QtWidgets.QFrame(self.centralwidget)
        self.bot.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bot.setStyleSheet("background-color: rgb(251, 190, 119);")
        self.bot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bot.setObjectName("bot")
        self.verticalLayout.addWidget(self.bot)
        TelaInicial.setCentralWidget(self.centralwidget)

        self.retranslateUi(TelaInicial)
        QtCore.QMetaObject.connectSlotsByName(TelaInicial)

    def retranslateUi(self, TelaInicial):
        _translate = QtCore.QCoreApplication.translate
        TelaInicial.setWindowTitle(_translate("TelaInicial", "GoldCoins"))
        self.StartButton.setText(_translate("TelaInicial", "Start"))
        self.label_12.setText(_translate("TelaInicial", "Já está cadastrado?"))
        self.LoginButton.setText(_translate("TelaInicial", "Entrar"))
#import images_rc
